# fly.toml app configuration file generated for stinyproxy on 2025-01-25T22:50:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stinyproxy'
primary_region = 'sin'

[build]

[[services]]
  auto_stop_machines = 'off'
  auto_start_machines = true
  internal_port = 443
  min_machines_running = 1
  protocol = 'tcp'

  [[services.ports]]
    handlers = []
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
